const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(__dirname+'/brain-regression.cjs','utf8');
const harness=vm.runInNewContext(source.slice(0,source.indexOf('const brain=harness'))+'\nharness',{require,__dirname,console,URLSearchParams,AbortController,AbortSignal});
const h=harness(['live.js','advanced-engine.js','draft-ai.js','team-roster.js']),m=h.context.window.RiftRoster;
h.run('userSide="blue";step=6;events=[]');
assert(h.run('window.RiftProfiles.get("Xerath").damage==="AP"'));
assert.equal(m.affinity('OBJECTIVE CONTROL','mid','Xerath').source,'kit');
assert.equal(m.affinity('PRESS R','mid','Xerath'),null,'ranged poke cannot replace primary engage');
m.addChampion('jungle','Gragas');m.setComfort('jungle','Gragas',9);
assert.equal(m.affinity('PRESS R','jungle','Gragas').source,'kit','not a per-comp hardcoded alternative');
assert(m.compOptions()['PRESS R'].jungle.includes('Gragas'));
assert(h.run('aiRoleCandidates("jungle").some(x=>x.ch==="Gragas")'));
assert.equal(m.affinity('PRESS R','adc','Gragas'),null,'role-inappropriate kits must not get affinity');
assert.equal(m.affinity('PRESS R','support','Braum'),null,'peel is not primary engage');
assert.equal(m.affinity('PRESS R','jungle','Unknown'),null,'never invent missing kits');
const plan=m.compPlan('PRESS R');plan.jungle='mutated';assert.notEqual(m.compPlan('PRESS R').jungle,'mutated');
m.pauseChampion('jungle','Gragas',true);assert(!m.compOptions()['PRESS R'].jungle.includes('Gragas'));
assert.notEqual(m.compPlan('PRESS R').jungle,'Gragas','cached plan invalidated');
m.pauseChampion('jungle','Gragas',false);
const id=m.savePlayer('jungle','','New',['Gragas','Diana'],false);
assert.equal(m.profile('jungle',id).comfort.Gragas,5,'new players must not inherit mastery');
m.renamePlayer('jungle',id,'Renamed');assert.equal(m.profile('jungle',id).name,'Renamed');
assert.equal(m.player('jungle').id,'core-jungle','renaming a reserve cannot select it');
assert.throws(()=>m.renamePlayer('jungle',id,''));
const reloaded=harness([],Object.fromEntries(h.storage));assert.equal(reloaded.context.window.RiftRoster.profile('jungle',id).name,'Renamed');
assert.equal(h.run('advStructure([{role:"support",champ:"Galio"},{role:"mid",champ:"Annie"}]).threats'),1);
const p=harness(['app.js']);p.context.window.RiftRoster.addChampion('jungle','Gragas');
assert(p.run('practiceAssignment(["Gragas"]).includes("jungle")'));
assert(p.run('comps["PRESS R"].alts.includes("Gragas")||comps["PRESS R"].core.includes("Gragas")'));
p.run('userSide="blue";picks=[{side:"blue",role:"support",champ:"Galio"},{side:"blue",role:"mid",champ:"Annie"}];updateScore()');
assert.equal(p.elements.get('damageScore').textContent,'1/3','support AP is not carry damage in practice');
// Check browser history behavior against real URL updates, including popstate.
const calls=[];p.context.history={replaceState:(state,unused,url)=>{calls.push('replace');const u=new URL(url,'https://test.invalid');p.context.location.pathname=u.pathname;p.context.location.search=u.search;},pushState:(state,unused,url)=>{calls.push('push');const u=new URL(url,'https://test.invalid');p.context.location.pathname=u.pathname;p.context.location.search=u.search;}};
p.run('setWorkspace("home");setWorkspace("planner");setWorkspace("trainer");setWorkspace("trainer")');
assert.deepEqual(calls,['replace','push','push']);
p.context.location.search='?workspace=planner';p.fire("window","popstate");
assert.equal(p.context.document.body.dataset.workspace,'planner');assert.equal(calls.length,3,'back cannot create a new history entry');
const visibility=new Set();p.elements.get('matchDayDashboard').classList={add:x=>visibility.add(x),remove:x=>visibility.delete(x)};
p.context.window.RiftBanPlanner={getPlans:()=>[{id:'future',status:'upcoming',scheduledAt:'2099-01-01',opponent:'Fixture'}]};
p.run('mode=null;document.body.dataset.workspace="planner";renderMatchDayDashboard()');assert(visibility.has('hidden'),'late match data must not reveal Home widgets in Planner');
p.run('showHomeView()');assert(!visibility.has('hidden'));
const start=performance.now();for(let i=0;i<1000;i++)m.compPlan('PRESS R');
assert(performance.now()-start<1500,'unchanged comp plans should reuse their search result');
console.log('PASS: kit-derived role-safe affinity, unknown-data safety, comfort default, rename/reload, cached plan invalidation, Brain/practice propagation, support damage and back/forward routing.');
