const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const original=fs.readFileSync(__dirname+'/brain-regression.cjs','utf8');
const harness=vm.runInNewContext(original.slice(0,original.indexOf('const brain=harness'))+'\nharness',{require,__dirname,console,URLSearchParams,AbortController,AbortSignal});
const h=harness(['live.js','advanced-engine.js','draft-ai.js','team-roster.js']);
h.run('userSide="blue";events=[];step=6');
const stable=(gap,key='same',urgent=0)=>h.run(`aiStableChoices([{ch:'Leona',role:'support',total:${100+gap},urgency:{points:${urgent}}},{ch:'Nautilus',role:'support',total:100,urgency:{points:0}}],${JSON.stringify(key)},{key:'same',ch:'Nautilus',role:'support'})[0].ch`);
assert.equal(stable(2),'Nautilus');assert.equal(stable(3),'Leona');assert.equal(stable(1,'changed'),'Leona');assert.equal(stable(1,'same',4),'Leona');
assert.equal(h.run("aiStableChoices([{ch:'Leona',role:'support',total:100}],'same',{key:'same',ch:'Nautilus',role:'support'})[0].ch"),'Leona');
const players=h.run('roles.map(role=>({role,id:window.RiftRoster.player(role).id}))');
const sample=(i,issue='peel')=>({id:'review-'+i,savedAt:new Date().toISOString(),result:i%2?'win':'loss',draftContext:{roster:{players}},postReview:{draftIssue:issue}});
const signal=()=>h.run('aiReviewSignal("Nautilus","support")');
h.storage.set('rs_match_history',JSON.stringify([sample(1),sample(2)]));assert.equal(signal().points,0);
h.storage.set('rs_match_history',JSON.stringify([sample(1),sample(2),sample(3)]));assert(signal().points>0&&signal().points<=2);
h.run('events=[{side:"blue",type:"pick",role:"top",champ:"Shen"}]');assert.equal(signal().points,0,'do not reward solving a solved need');h.run('events=[]');
h.storage.set('rs_match_history',JSON.stringify([sample(1),sample(1),sample(1)]));assert.equal(signal().points,0,'duplicates cannot create a trend');
h.storage.set('rs_match_history',JSON.stringify([1,2,3].map(i=>({...sample(i),savedAt:'2020-01-01'}))));assert.equal(signal().points,0);
h.storage.set('rs_match_history',JSON.stringify([1,2,3].map(i=>({...sample(i),postReview:{difficult:'saknar peel'}}))));assert.equal(signal().points,0,'free text must not be treated as confirmed draft evidence');
h.storage.set('rs_match_history',JSON.stringify([sample(1),sample(2),sample(3)]));h.run('window.RiftRoster.select("support","jacob-support")');assert.equal(signal().points,0,'another five must not inherit this trend');
h.storage.set('rs_match_history','[null,{}]');assert.equal(signal().points,0);
h.run('window.RiftRoster.select("support","core-support")');
const clear=h.run('aiExecution({top:"Malphite",jungle:"Jarvan IV",mid:"Annie",adc:"Jinx",support:"Leona"})');assert(clear.points>0);
h.run('comfort.mid.Annie=3;comfort.adc.Jinx=3');assert(h.run('aiExecution({top:"Malphite",jungle:"Jarvan IV",mid:"Annie",adc:"Jinx",support:"Leona"}).points')<clear.points);
// Observed replacement depth affects ban value, but an absent pool is not invented.
const plan={id:'fixture',status:'upcoming',competitiveEvidence:{currentRoster:[{riotId:'M#1',role:'mid'}]},scoutingPlayers:[{riotId:'M#1',tier:'GOLD',topChampions:[{champ:'Ahri',seasonGames:100,recentGames:10},{champ:'Annie',seasonGames:1,recentGames:0}]}]};
const scout=harness(['live.js','advanced-engine.js','draft-ai.js','scouting-lineup.js','brain-opponent.js'],{'rs_ban_plans_cache':JSON.stringify([plan]),'rs_brain_opponent':'fixture'});scout.fire('document','DOMContentLoaded');scout.run('userSide="blue";events=[];step=0');
const shallow=scout.run('window.RiftOpponent.banScore("Ahri")');
assert(scout.run('window.RiftOpponent.banReason("Ahri")').includes('Annie'));
scout.run('Object.assign(window.RiftOpponent.active().scoutingPlayers[0].topChampions[1],{seasonGames:100,recentGames:10})');assert(scout.run('window.RiftOpponent.banScore("Ahri")')<shallow);
scout.run('window.RiftOpponent.active().scoutingPlayers[0].topChampions.pop()');assert(scout.run('window.RiftOpponent.banReason("Ahri")').includes('Alternativ saknas'));
const reliable=scout.run('window.RiftOpponent.prospects()[0].weight');scout.run('Object.assign(window.RiftOpponent.active().scoutingPlayers[0].topChampions[0],{seasonGames:1,recentGames:0})');assert(scout.run('window.RiftOpponent.prospects()[0].weight')<reliable);
console.log('PASS: stable ties, meaningful changes, illegal removal, explicit repeated review only, roster isolation, deduplication, recency, solved needs, execution comfort, replacement bans and sample uncertainty.');
