const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const src=fs.readFileSync(__dirname+'/brain-regression.cjs','utf8');
const harness=vm.runInNewContext(src.slice(0,src.indexOf('const brain=harness'))+'\nharness',{require,__dirname,console,URLSearchParams,AbortController,AbortSignal});
const h=harness(['live.js','advanced-engine.js','draft-ai.js','team-roster.js']);
h.run('userSide="blue";events=[];step=6');
assert.equal(h.run('aiCompPreference({},"TEAMFIGHT CONTROL")'),12);
assert.equal(h.run('aiCompPreference({},"EARLY SKIRMISH")'),12);
assert.equal(h.run('aiCompPreference({},"PRESS R")'),0);
h.run('events=[{type:"pick",side:"blue",role:"jungle",champ:"Jarvan IV"},{type:"pick",side:"blue",role:"mid",champ:"Viktor"}]');
assert.equal(h.run('desiredComp()'),'TEAMFIGHT CONTROL');
assert(h.run('buildFinalGameplan().mid.includes("Jarvan")'));
assert(!h.run('window.RiftRoster.compOptions()["TEAMFIGHT CONTROL"].top.includes("Sion")'));
assert.equal(h.run('JSON.stringify(window.RiftRoster.compOptions()["TEAMFIGHT CONTROL"].mid.sort())'),JSON.stringify(['Hwei','Viktor']));
const old=h.run('aiRoleCandidates("adc").find(c=>c.ch==="Xayah").score-aiRoleCandidates("adc").find(c=>c.ch==="Jinx").score');
h.run('events.push({type:"pick",side:"red",champ:"Vi",role:"jungle"},{type:"pick",side:"red",champ:"Malphite",role:"top"})');
const dive=h.run('aiRoleCandidates("adc").find(c=>c.ch==="Xayah").score-aiRoleCandidates("adc").find(c=>c.ch==="Jinx").score');
assert(dive>old,'enemy dive must improve Xayah relative to Jinx');
h.run('window.RiftRoster.select("support","jacob-support")');
assert(h.run('window.RiftRoster.compOptions()["TEAMFIGHT CONTROL"].support.includes("Braum")'));
h.run('window.RiftRoster.pauseChampion("support","Braum",true)');assert(!h.run('window.RiftRoster.compOptions()["TEAMFIGHT CONTROL"].support.includes("Braum")'));
h.run('events=[{type:"ban",side:"red",champ:"Viktor"}]');assert.equal(h.run('aiCompPreference({},"TEAMFIGHT CONTROL")'),12);
h.run('events.push({type:"ban",side:"blue",champ:"Hwei"})');assert.equal(h.run('aiCompPreference({},"TEAMFIGHT CONTROL")'),0);assert.equal(h.run('aiCompPreference({},"PRESS R")'),0,'early plan still available');
h.run('events.push({type:"pick",side:"blue",role:"mid",champ:"Annie"})');assert.equal(h.run('aiCompPreference(ownRoleMap(),"PRESS R")'),8);
const p=harness(['app.js']);assert.equal(p.run('bestComp(["Malphite","Jarvan IV","Viktor","Jinx","Nautilus"]).name'),'TEAMFIGHT CONTROL');
p.run('openCompGuide("TEAMFIGHT CONTROL")');assert.equal(p.elements.get('compGuideTitle').textContent,'Teamfight Control');
(async()=>{const policy=await import('../supabase/functions/rift-draft-coach/policy.mjs');const d=policy.sanitizeDraft({side:'blue',events:[],pools:{mid:['Hwei']},compOptions:{'TEAMFIGHT CONTROL':{mid:['Hwei','Ahri']}},candidates:[{ch:'Garen'}]});assert.deepEqual(d.compOptions['TEAMFIGHT CONTROL'].mid,['Hwei']);assert(d.comps.includes('TEAMFIGHT CONTROL'));console.log('PASS: two primary comps, Jarvan/mage identity, contextual Xayah, active subs, paused champs, fallback gates, guide and AI payload.');})().catch(e=>{console.error(e);process.exitCode=1;});
